name: Sync GitHub Issues to Notion

on:
  issues:
    types: [opened, edited, deleted, labeled, unlabeled, assigned, unassigned, closed, reopened]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Use my Notion Sync Action
      uses: Gisat/ptr-github-issues-for-notion@wip
      with:
        notion-token: ${{ secrets.NOTION_TOKEN }}
        notion-db: ${{ secrets.NOTION_DATABASE }}
        github-token: ${{ secrets.GH_TOKEN }}